language: bash
sudo: false
install: true

addons:
  apt:
    packages:
    - lua5.1
    - python2.7

script: "[[ -n $TRAVIS_TAG ]] && ./build.sh web android || ./build.sh" # web and android only for tags    
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <token> 
    secure: SuFYLO+qAR5MjK7VrE/yMv2Bg1agFYHAfI5zdJmVy5fRWnul4pkQy6qorzhZiionHOk82z/n8A7Od3DVS/UqcSrpT+j59jeTt3xHe0z31OK7xvQedu/TswQKLRk3AhSne0sfXG0nsEsd96WjOT7rMphTGYXVm8xZcK6oskeLKxpM1ergYcxsqhx67xQGLf1T4UKgiHABE7wxnSdyoESxmhQUgfBy6ZVR7At7HkUiAU/VK7Y5SZS8/HfCGk+PGhwAayyT6fu3NiTaVmbUSuT3ASCFov8keLrWztVRxyCzv9MjkWvbh6KMoCsdLNI8rrZP0Gm1F7rV+pIosivYU71ndoJ3iRTGqTrF9uxS8nFUnP5r+9+IfnXXtMVoz1zNtxmhfwa0JGey3JFhgjK/NOgW84npIRzrzZzxJkJb/3UEjPM2SLNDpS2zh6lzGnTslKGenCJvNBHB5xgnXPfhu5Oq7V56/QplG+FawAn8BMyXmclAvd6xqDY6CHEnOjIxiJHC8fk/+czhCfy59UDHItUBb8nefHHSq7w+OVc3UAUnT5wM5LS2PaXxPfY/h4AgOcD6GDfIphAo1axVkBg2j01qnvaPZU5OXbTGci6CuosKT/3pE9G/hVF9ifvTsXyk5zExnyhKWZdrh9zxrESgtZ0BXRceZNBUshcxKWB6ht0deto=
  file:
  - target/floppy_dirk.love
  - target/floppy_dirk-win.zip
  - target/floppy_dirk-web.zip
  - target/floppy_dirk-debug.apk
  - target/floppy_dirk-release-unsigned.apk
  on:
    tags: true
    all_branches: true
after_success:
- "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy $TRAVIS_REPO_SLUG"
env:
  global:
   # travis encrypt GH_TOKEN=<token>
  - secure: gBf+Se51Zjp5Dan+r2T8wTWf9VMxxPTX7+/5jAZQ8vqEJ5UJ+W9kbTXqe1FI66Yfe9SlF3rhTwfw7MtFuXIaDPYbP8smSOGshb7AiTaqZ02oLh+sm4w8/3OrC9yY4/BCfZmv/H+rNlsGYibfz9gFEAzzUME4qeoZ7D8R8oiiGfWFOfgRnv2Z4T6BO54XUjk9j2710vO/54zAzUMv4+enhnKetqV2g5q5/zBlRYm18xIN7vS7Sj5u9l2w33urxToA8eODZq0YTPasCYr6yp6sqEhPx7m1FRWKzvnPdftZ5ipws7iDR1ngaLulb/bzge+C3t1O3q7gfMge3n3Z2MqeVDw45PaufyEzYHjLo4GmouD7rAjneifOMWgL0wPA5l3E+RHOKFJbDFLDmr7ovBuuIg56ppaA8r5AlC4OWyNKvZ9ipyYFMWqdgIlJ23WIrw7Cmm8CIOz3s6wxCMla/6s1oHZrdbPSt81mZ0xdpgVzue+MPT1mFwNxwNmOqbs4LjvKUAfGN8FQoIyj0bTrxi1pEYNH7M+ZN40iXr+fpgKLteGjwDaLX+c1N8dOXGTZQin4JqkS5+6d2QKavOP1EoJyRGigrYScpQkcS5nqOcipHvNx96qQTFNKCnlZokNlW3PPizMs+Jjlulc8Abd+VwQiBpJvvz06aMJqsD5jYkgACFI=